### ISSUE TITLE
Resource requests should include requesting URL

### ISSUE THREAD

**Issue by pushred** [solidusjs/solidus-client#11]
Resources currently have no knowledge of how requested data is being used beyond any API key and associated details. We should include the requesting URL as a header in resource requests for use in tracking usage. This would particularly be valuable to proxies like storyteller.io which could invalidate caches such as those of a CDN based on these dependent URLs.

`Referer` could make sense but may not be semantically correct in this context. A non-standard `X-Requested-By` could be another option.

**Comment by joanniclaborde** [comment]
I went with `Referer`, since it is already set for the browser resources. For server resources, see https://github.com/solidusjs/solidus/pull/135.
